import pandas as pd
preg2=pd.read_excel('BI_Clientes.xlsx')
print('Cálculos de tendencia centarl')
min=pd.DataFrame(preg2['YearlyIncome']).min()
max=pd.DataFrame(preg2['YearlyIncome']).max()
media=pd.DataFrame(preg2['YearlyIncome']).mean()
mediana=pd.DataFrame(preg2['YearlyIncome']).median()
moda=pd.DataFrame(preg2['YearlyIncome']).mode()
completo=pd.DataFrame(preg2['YearlyIncome']).describe()


print("-----------PREGUNTA 2.1----------------")
print("---------EL MÍNIMO-----------")
print(min)
print("")
print("---------EL MÁXIMO-----------")
print(max)
print("")
print("---------LA MEDIA ARITMÉTICA-----------")
print(media)
print("")
print("---------LA MEDIANA-----------")
print(mediana)
print("")
print("---------LA MODA-----------")
print(moda)
print("")
print("---------LOS DATOS GENERALES-----------")
print(completo)
print("")

print("----------------------PREGUNTA 2.2----------")
print("LA MEDIA ES: ",preg2['TotalChildren'].mean())
print("LA MODA ES: ",preg2['TotalChildren'].mode())
print("LA MEDIANA ES: ",preg2['TotalChildren'].median())
